[package]
name = "headlines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.5"
eframe = "0.20.0"
serde = {version="1", features = ["derive"]}
tracing = "0.1"
tracing-subscriber = "0.3"
newsapi = {path = "../newsapi"}